version: '3.8'

services:
  db-ms-user:
    container_name: c-ms-user-db
    image: postgres:latest
    environment:
      POSTGRES_USER: asim
      POSTGRES_PASSWORD: asim123
      POSTGRES_DB: user_db
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - shared-net
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "asim", "-d" , "user_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  ma-user-app:
    container_name: c-ms-user-app
    image: ms-user:0.1
    ports:
      - 6223:6223
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-ms-user:5432/user_db
      - SPRING_DATASOURCE_USERNAME=asim
      - SPRING_DATASOURCE_PASSWORD=asim123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      db-ms-user:
        condition: service_healthy
    networks:
      - shared-net
networks:
  shared-net:
    driver: bridge