spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms_user_db
    username: guest
    password: guest
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
