spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: asim
    password: asim123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
