spring:
  application:
    name: ms-user

  datasource:
    url: jdbc:postgresql://localhost:5432/ms_user_db
    username: guest
    password: guest
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: ms-user-group
      auto-offset-reset: earliest

  security:
    oauth2:
      resourceserver:
        jwt:
          # ms-auth tərəfindən verilən JWK URI
          jwk-set-uri: http://localhost:8081/.well-known/jwks.json

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.kafka: INFO
